%% Init
ref_elements_st = struct;
ref_elements_st.ref_model_name = 'create_turn_vehicle_ref';
ref_elements_st.cycloid_model_name = 'create_cycloid_vehicle_ref';
ref_elements_st.ref_SE_name = [ref_elements_st.ref_model_name, '/input_signal'];
ref_elements_st.ref_cyc_SE_name = [ref_elements_st.cycloid_model_name, ...
    '/input_signal'];

ref_signals_st = struct;
ref_signals_st.elements_file = './others/ref_elements_signal.mat';
ref_signals_st.silgnals_file = './common/ref_signal_vehicle.mat';

end_time_unstable_system = 60;
my_sldd_obj = Simulink.data.dictionary.open('sim_data_unstable_system.sldd');
data_set_obj = getSection(my_sldd_obj, 'Design Data');
data_entry = getEntry(data_set_obj, 'SimEndTime');
endtime_obj = getValue(data_entry);
endtime_obj.Value = end_time_unstable_system;
setValue(data_entry, endtime_obj);
saveChanges(my_sldd_obj);

end_time_vehicle = 110;
my_sldd_obj = Simulink.data.dictionary.open('sim_data_vehicle.sldd');
data_set_obj = getSection(my_sldd_obj, 'Design Data');
data_entry = getEntry(data_set_obj, 'SimEndTime');
endtime_obj = getValue(data_entry);
endtime_obj.Value = end_time_vehicle;
setValue(data_entry, endtime_obj);
saveChanges(my_sldd_obj);

load_system(ref_elements_st.ref_model_name);
load_system(ref_elements_st.cycloid_model_name);

%% turn vehicle
ref_elements_st.turn_vehicle.r.t = [...
    0; 30; 30; 40; 40; 70; 70; 80; 80; end_time_vehicle];
ref_elements_st.turn_vehicle.r.v = [...
    0; 0; pi/10; pi/10; 0; 0; -pi/10; -pi/10; 0; 0];
ref_elements_st.turn_vehicle.V.t = [...
    0; end_time_vehicle];
ref_elements_st.turn_vehicle.V.v = [...
    2; 2];

%% turn cycloid vehicle
ref_elements_st.turn_cycloid_vehicle.r.t = [...
    0; 30; 30; 40; 40; 70; 70; 80; 80; end_time_vehicle];
ref_elements_st.turn_cycloid_vehicle.r.v = [...
    0; 0; pi/10; pi/10; 0; 0; -pi/10; -pi/10; 0; 0];
ref_elements_st.turn_cycloid_vehicle.cycloid_flag.t = [...
    0; 30; 30; 40; 40; 70; 70; 80; 80; end_time_vehicle];
ref_elements_st.turn_cycloid_vehicle.cycloid_flag.v = boolean([...
    0; 0; 1; 1; 0; 0; 1; 1; 0; 0]);
ref_elements_st.turn_cycloid_vehicle.V.t = [...
    0; end_time_vehicle];
ref_elements_st.turn_cycloid_vehicle.V.v = [...
    2; 2];

%% regular circle turning vehicle
ref_elements_st.regular_circle.r.t = [
    0; end_time_vehicle];
ref_elements_st.regular_circle.r.v = [
    pi/10; pi/10];
ref_elements_st.regular_circle.V.t = [...
    0; end_time_vehicle];
ref_elements_st.regular_circle.V.v = [...
    2; 2];

%% change vehicle dirction
ref_elements_st.ch_dir_vehicle.r.t = [...
    0; 40; 40; 45; 45; 100];
ref_elements_st.ch_dir_vehicle.r.v = [...
    0; 0; pi/10; pi/10; 0; 0];
ref_elements_st.ch_dir_vehicle.V.t = [...
    0; 100];
ref_elements_st.ch_dir_vehicle.V.v = [...
    1; 1];

%% update ref elements signal
load(ref_signals_st.elements_file);

elements_of_turn_vehicle{1}.Values.Time = ...
    ref_elements_st.turn_vehicle.r.t;
elements_of_turn_vehicle{1}.Values.Data = ...
    ref_elements_st.turn_vehicle.r.v;
elements_of_turn_vehicle{2}.Values.Time = ...
    ref_elements_st.turn_vehicle.V.t;
elements_of_turn_vehicle{2}.Values.Data = ...
    ref_elements_st.turn_vehicle.V.v;

elements_of_ch_dir_vehicle{1}.Values.Time = ...
    ref_elements_st.ch_dir_vehicle.r.t;
elements_of_ch_dir_vehicle{1}.Values.Data = ...
    ref_elements_st.ch_dir_vehicle.r.v;
elements_of_ch_dir_vehicle{2}.Values.Time = ...
    ref_elements_st.ch_dir_vehicle.V.t;
elements_of_ch_dir_vehicle{2}.Values.Data = ...
    ref_elements_st.ch_dir_vehicle.V.v;

elements_of_regular_circle_vehicle{1}.Values.Time = ...
    ref_elements_st.regular_circle.r.t;
elements_of_regular_circle_vehicle{1}.Values.Data = ...
    ref_elements_st.regular_circle.r.v;
elements_of_regular_circle_vehicle{2}.Values.Time = ...
    ref_elements_st.regular_circle.V.t;
elements_of_regular_circle_vehicle{2}.Values.Data = ...
    ref_elements_st.regular_circle.V.v;

elements_of_cycloid_turn_vehicle{1}.Values.Time = ...
    ref_elements_st.turn_cycloid_vehicle.r.t;
elements_of_cycloid_turn_vehicle{1}.Values.Data = ...
    ref_elements_st.turn_cycloid_vehicle.r.v;
elements_of_cycloid_turn_vehicle{2}.Values.Time = ...
    ref_elements_st.turn_cycloid_vehicle.V.t;
elements_of_cycloid_turn_vehicle{2}.Values.Data = ...
    ref_elements_st.turn_cycloid_vehicle.V.v;
elements_of_cycloid_turn_vehicle{3}.Values.Time = ...
    ref_elements_st.turn_cycloid_vehicle.cycloid_flag.t;
elements_of_cycloid_turn_vehicle{3}.Values.Data = ...
    ref_elements_st.turn_cycloid_vehicle.cycloid_flag.v;

save(ref_signals_st.elements_file, ...
    'elements_of_turn_vehicle', ...
    'elements_of_ch_dir_vehicle', ...
    'elements_of_cycloid_turn_vehicle', ...
    'elements_of_regular_circle_vehicle');

%% simulate and get ref signal
set_param(ref_elements_st.ref_SE_name, 'ActiveScenario', ...
    'elements_of_turn_vehicle');
turn_vehicle_ref_data = sim(ref_elements_st.ref_model_name);

set_param(ref_elements_st.ref_SE_name, 'ActiveScenario', ...
    'elements_of_ch_dir_vehicle');
ch_dir_vehicle_ref_data = sim(ref_elements_st.ref_model_name);

set_param(ref_elements_st.ref_SE_name, 'ActiveScenario', ...
    'elements_of_regular_circle_vehicle');
regular_circle_vehicle_ref_data = sim(ref_elements_st.ref_model_name);

set_param(ref_elements_st.ref_cyc_SE_name, 'ActiveScenario', ...
    'elements_of_cycloid_turn_vehicle');
cycloid_turn_vehicle_ref_data = sim(ref_elements_st.cycloid_model_name);


%% update ref signal
load(ref_signals_st.silgnals_file);

for i = 1:turn_vehicle.numElements
    turn_vehicle{i}.Values.Time = ...
        turn_vehicle_ref_data.yout{i}.Values.Time;
    turn_vehicle{i}.Values.Data = ...
        turn_vehicle_ref_data.yout{i}.Values.Data;
end

for i = 1:cycloid_turn_vehicle.numElements
    cycloid_turn_vehicle{i}.Values.Time = ...
        cycloid_turn_vehicle_ref_data.yout{i}.Values.Time;
    cycloid_turn_vehicle{i}.Values.Data = ...
        cycloid_turn_vehicle_ref_data.yout{i}.Values.Data;
end

for i = 1:regular_circle_turn_vehicle.numElements
    regular_circle_turn_vehicle{i}.Values.Time = ...
        regular_circle_vehicle_ref_data.yout{i}.Values.Time;
    regular_circle_turn_vehicle{i}.Values.Data = ...
        regular_circle_vehicle_ref_data.yout{i}.Values.Data;
end

for i = 1:ch_dir_vehicle.numElements
    ch_dir_vehicle{i}.Values.Time = ...
        ch_dir_vehicle_ref_data.yout{i}.Values.Time;
    ch_dir_vehicle{i}.Values.Data = ...
        ch_dir_vehicle_ref_data.yout{i}.Values.Data;
end

save(ref_signals_st.silgnals_file, ...
    'control_y_V', ...
    'turn_vehicle', ...
    'ch_dir_vehicle', ...
    'cycloid_turn_vehicle', ...
    'regular_circle_turn_vehicle');

%% Terminate
save_system(ref_elements_st.ref_model_name);

